let categoryData = {
    "Actor": "31",
    "Actress": "32",
    "Female Anchor": "24",
    "Female Art Director": "54",
    "Female Associate Director": "46",
    "Female Celebrity": "57",
    "Female Character Artist": "22",
    "Female Child Artist": "50",
    "Female Choreography": "43",
    "Female Cinematography": "42",
    "Female Comedian": "40",
    "Female Director": "44",
    "Female Dubbing Artist": "48",
    "Female Editor": "63",
    "Female Fresh Face": "29",
    "Female Hyderabad Model": "56",
    "Female Lyricist": "51",
    "Female Make-Up": "41",
    "Female Model": "16",
    "Female Music Director": "53",
    "Female Producer": "61",
    "Female Screenplay Writer": "45",
    "Female Singer": "23",
    "Female TV Star": "59",
    "Female Villian": "47",
    "Female Writer": "52",
    "Item Girl": "20",
    "Male Character Artist": "21",
    "Male Anchor": "49",
    "Male Art Director": "10",
    "Male Associate Director": "27",
    "Male Celebrity": "58",
    "Male Child Artist": "14",
    "Male Choreography": "35",
    "Male Cinematography": "37",
    "Male Comedian": "39",
    "Male Director": "34",
    "Male Dubbing Artist": "25",
    "Male Editor": "62",
    "Male Fresh Face": "30",
    "Male Hyderabad Model": "55",
    "Male Lyricist": "13",
    "Male Make-Up": "38",
    "Male Model": "15",
    "Male Music Director": "11",
    "Male Screenplay Writer": "28",
    "Male Singer": "33",
    "Male Stunt": "36",
    "Male TV Star": "60",
    "Male Villian": "26",
    "Male Writer": "12",
    "Other": "19",
    "Producer": "17",
    "Production House": "18"
}